# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: build-without-local-llms

on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  build-and-push-image:
    name: Push Docker image to Docker Hub and Aliyun
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Read version from file
        id: get_version
        run: |
          echo "VERSION=$(python -c "import json; print(json.load(open('version'))['version'])")" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker Hub
        id: meta_docker_hub
        uses: docker/metadata-action@v5
        with:
          images: cqvip/gpt_academic_nolocal
          tags: type=raw,value=master

      - name: Extract metadata for Aliyun
        id: meta_aliyun
        uses: docker/metadata-action@v5
        with:
          images: registry.cn-beijing.aliyuncs.com/chsi/gpt_academic_nolocal
          tags: |
            type=raw,value=master
            type=raw,value=${{ steps.get_version.outputs.VERSION }}
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs/GithubAction+NoLocal
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_docker_hub.outputs.tags }}
          labels: ${{ steps.meta_docker_hub.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image to Aliyun
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs/GithubAction+NoLocal
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_aliyun.outputs.tags }}
          labels: ${{ steps.meta_aliyun.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max